name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
      - 'hotfix'
  - title: '🧰 Maintenance'
    labels:
      - 'refactor'
      - 'enhancement'
      - 'chore'
  - title: '📃 Documentation'
    label: 'documentation'
exclude-labels:
  - 'skip-changelog'
replacers:
  - search: '/FN-(\d{1,4})/g'
    replace: '[FN-$1](https://betconstruct.atlassian.net/browse/FN-$1)'
autolabeler:
  - label: 'bugfix'
    branch:
      - '/bug(?:fix)?/'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'release'
    branch:
      - '/release\/.+/'
  - label: 'experimental'
    branch:
      - '/experimental\/.+/'
  - label: 'skip-changelog'
    branch:
      - '/(main|develop|experimental).*/'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'release'
  patch:
    labels:
      - 'hotfix'
publish: true
latest: 'true'
template: |
  ## Changes

  $CHANGES
change-template: '* $TITLE'
