name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"
autolabeler:
  - label: "bugfix"
    branch:
      - "/bug(?:fix)?/"
  - label: "release"
    branch:
      - '/release\/.+/'
  - label: "skip-changelog"
    branch:
      - "/(develop|experimental).*/"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "release"
  patch:
    labels:
      - "hotfix"
publish: true
latest: "true"
template: |
  ## Changes

  $CHANGES
change-template: "* $TITLE"
