name: Release Drafter

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - "release/*"

permissions:
  contents: write

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
